// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Presupuesto.Infrastructure.Database;

#nullable disable

namespace Presupuesto.Infrastructure.Database.Migrations
{
    [DbContext(typeof(PresupuestoDbContext))]
    [Migration("20260722025132_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Presupuesto.Domain.Transacciones.Transaccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en_utc");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Fecha");

                    b.ToTable("transacciones", (string)null);
                });

            modelBuilder.Entity("Presupuesto.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Presupuesto.Domain.Transacciones.Transaccion", b =>
                {
                    b.HasOne("Presupuesto.Domain.Usuarios.Usuario", null)
                        .WithMany("Transacciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Presupuesto.Domain.Transacciones.Categoria", "Categoria", b1 =>
                        {
                            b1.Property<Guid>("TransaccionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("categoria");

                            b1.HasKey("TransaccionId");

                            b1.ToTable("transacciones");

                            b1.WithOwner()
                                .HasForeignKey("TransaccionId");
                        });

                    b.OwnsOne("Presupuesto.Domain.Transacciones.Descripcion", "Descripcion", b1 =>
                        {
                            b1.Property<Guid>("TransaccionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("descripcion");

                            b1.HasKey("TransaccionId");

                            b1.ToTable("transacciones");

                            b1.WithOwner()
                                .HasForeignKey("TransaccionId");
                        });

                    b.OwnsOne("Presupuesto.Domain.Transacciones.Dinero", "Monto", b1 =>
                        {
                            b1.Property<Guid>("TransaccionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("monto");

                            b1.HasKey("TransaccionId");

                            b1.ToTable("transacciones");

                            b1.WithOwner()
                                .HasForeignKey("TransaccionId");
                        });

                    b.Navigation("Categoria")
                        .IsRequired();

                    b.Navigation("Descripcion")
                        .IsRequired();

                    b.Navigation("Monto")
                        .IsRequired();
                });

            modelBuilder.Entity("Presupuesto.Domain.Usuarios.Usuario", b =>
                {
                    b.OwnsOne("Presupuesto.Domain.Usuarios.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Presupuesto.Domain.Usuarios.Nombre", "Nombre", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("nombre");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Nombre")
                        .IsRequired();
                });

            modelBuilder.Entity("Presupuesto.Domain.Usuarios.Usuario", b =>
                {
                    b.Navigation("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
